Controllers/BaoHiemTuNguyenController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebTools.Models.Entities;
using WebTools.Services.Interface;

namespace WebTools.Controllers
{
    [Authorize]
    public class BaoHiemTuNguyenController : Controller
    {
        private readonly IBaoHiemTuNguyenServices _baoHiemTuNguyenServices;
        public BaoHiemTuNguyenController(IBaoHiemTuNguyenServices baoHiemTuNguyenServices)
        {
            _baoHiemTuNguyenServices = baoHiemTuNguyenServices;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult KhachHangThanhToanBHTN()
        {
            return View();
        }
        public IActionResult BangKeChiPhi()
        {
            return View();
        }
        public async Task<JsonResult> SearchKhanhHangThanhToanBHTN(string mabn, string loai, string ngayBD, string ngayKT)
        {
            var data = (await _baoHiemTuNguyenServices.SearchKhanhHangThanhToanBHTN(mabn, loai, ngayBD, ngayKT)).ToList();
            return Json(new { data });
        }
    }
}

Controllers/PermissionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using WebTools.Authorization;
using WebTools.Models;
using WebTools.Models.Entities;
using WebTools.Models.Entity;
using WebTools.Services.Interface;

namespace WebTools.Controllers
{
    [Authorize(Roles = "Admin")]
    //[Authorize(Policy = "AdminOnly")]
    /// <summary>
    /// Permission Users, Roles, ModuleControllers, ModuleActions
    /// </summary>
    #region Connection Database

    public class PermissionController : Controller
    {
        private readonly IUserServices _userServices;
        private readonly IRolesServices _roleServices;
        private readonly IModuleControllerServices _moduleControllerServices;
        private readonly IModuleActionServices _moduleActionServices;

        public PermissionController(IUserServices userServices, IRolesServices roleServices, IModuleControllerServices moduleControllerServices, IModuleActionServices moduleActionServices)
        {
            _userServices = userServices;
            _roleServices = roleServices;
            _moduleControllerServices = moduleControllerServices;
            _moduleActionServices = moduleActionServices;
        }

        #endregion

        #region Permission
        //Tạo chuỗi Permission từ Controller và Actions
        public List<string> GeneratePermissionsForModule(int controllerID)
        {
            var permissionList = new List<string>();
            var controllerData = _moduleControllerServices.GetModuleControllersByID(controllerID);
            foreach(var action in _moduleActionServices.GetActionsInController(controllerID))
            {
                string permissionString = $"Permissions.{controllerData.ControllerName}.{action.ActionName}";
                permissionList.Add(permissionString);
            }
            return permissionList;
        }
        #endregion
        public IActionResult Index()
        {
            return View();
        }

        #region User
        //[ControllerModelConvention]
        public IActionResult Users()
        {
            UsersViewModel model = new UsersViewModel();
            model.UsersList = _userServices.GetAllUsers();
            //model.Roles = new SelectList(_roleServices.GetAllRoles(), "RoleID", "RoleName");
            model.RolesList = _roleServices.GetAllRoles();
            return View(model);
        }


        [HttpGet]
        //[ControllerModelConvention]
        public IActionResult UserRoles(int? id)
        {
            var viewModel = new List<Roles>();
            var user = _userServices.GetUsersByID(id);
            foreach (var role in _roleServices.GetAllRoles())
            {
                var roles = new Roles
                {
                    RoleID = role.RoleID,
                    RoleName = role.RoleName,
                    Description = role.Description,
                };
                if (_userServices.IsUserInRole(user.UserID, role.RoleID))
                {
                    roles.Status = true;
                }
                else
                {
                    roles.Status = false;
                }
                viewModel.Add(roles);
            }

            UsersViewModel model = new UsersViewModel();
            model.RolesList = viewModel;
            model.Users = _userServices.GetUsersByID(id);

            return PartialView("_UserRolesPartial", model);
        }

        [HttpPost]
        public IActionResult EditUserRole(UserRoles userRoles)
        {
            int count = Int32.Parse(Request.Form["count"]);
            if (count > 0) 
            {
                _userServices.DeleteRoleInUser(userRoles.UserID);
                _userServices.DeleteUserPermissions(userRoles.UserName);
            }
            for (int i = 0; i < count; i++)
            {
                userRoles.UserID = Int32.Parse(Request.Form["UserID-" + i]);
                userRoles.RoleID = Int32.Parse(Request.Form["RoleID-" + i]);
                userRoles.RoleName = Request.Form["RoleName-" + i];
                userRoles.Description = Request.Form["Description-" + i];
                userRoles.Status = Boolean.TryParse(Request.Form["Status-" + i], out bool b);
                if (userRoles.UserID > 0 && userRoles.RoleID > 0 && userRoles.Status == true)
                {
                    var result = _userServices.AddUserRolesByID(userRoles);
                    UserPermissions userPermissions = new UserPermissions();
                    
                    foreach (var permission in _roleServices.GetRolePermissions(userRoles.RoleID))
                    {
                        userPermissions = new UserPermissions()
                        {
                            UserName = userRoles.UserName,
                            Permission = permission.Permission,
                            ControllerID = permission.ControllerID,
                            ActionID = permission.ActionID,
                        };
                        _userServices.AddUserPermissions(userPermissions);
                    }    

                    if (result == "OK")
                    {
                        TempData["SuccessMsg"] = $"Người dùng đã được cập nhật lại Role thành công!";
                    }
                    else
                    {
                        TempData["ErrorMsg"] = "Lỗi! " + result;
                    }
                }
            }

            return RedirectToAction("Users");

        }
        #endregion

        #region Roles
        /// <summary>
        /// Quản lý vai trò
        /// </summary>
        public IActionResult Roles()
        {
            RoleControllerActionViewModel model = new RoleControllerActionViewModel();
            model.RolesList = _roleServices.GetAllRoles();
            model.Roles = null;
            return View(model);
        }

        [HttpGet]
        public IActionResult EditRoles(int? id)
        {
            RoleControllerActionViewModel model = new RoleControllerActionViewModel();
            model.Roles = _roleServices.GetRolesByID(id);
            return PartialView("_EditRolePartial", model);
        }
        [HttpPost]
        public IActionResult EditRoles(Roles roles)
        {
            roles.ModifiedBy = User.Identity.Name;
            roles.DateModified = DateTime.Today;

            if (roles.RoleID > 0 && roles.RoleName != null)
            {
                var result = _roleServices.EditRoles(roles);
                if (result == "OK")
                {
                    TempData["SuccessMsg"] = $"Role: {roles.RoleName} đã được cập nhật lại thông tin thành công!";
                }
                else
                {
                    TempData["ErrorMsg"] = "Lỗi! " + result;
                }
                return RedirectToAction("Roles");
            }
            TempData["ErrorMsg"] = $"Lỗi! Không tìm thấy thông tin Roles: {roles.RoleName}";
            return RedirectToAction("Roles");
        }

        [HttpPost]
        public IActionResult CreateRoles(Roles roles)
        {
            roles.CreatedBy = User.Identity.Name;
            roles.DateCreated = DateTime.Today;

            if (roles.RoleName != null)
            {
                var result = _roleServices.AddRoles(roles);
                if (result == "OK")
                {
                    TempData["SuccessMsg"] = $"Thêm Role: {roles.RoleName} thành công!";
                }
                else
                {
                    TempData["ErrorMsg"] = "Lỗi! " + result;
                }
                return RedirectToAction("Roles");
            }
            TempData["ErrorMsg"] = "Lỗi! Không thể thêm Roles";
            return RedirectToAction("Roles");
        }

        public IActionResult DeleteRoles(int? id)
        {
            RoleControllerActionViewModel model = new RoleControllerActionViewModel();
            model.Roles = _roleServices.GetRolesByID(id);
            if (id != null)
            {
                var result = _roleServices.DeleteRoles(id);
                if (result == "OK")
                {
                    TempData["SuccessMsg"] = "Xóa Role: " + model.Roles.RoleName + " thành công!";
                }
                else
                {
                    TempData["ErrorMsg"] = "Lỗi! " + result;
                }
                return RedirectToAction("Roles");
            }
            TempData["ErrorMsg"] = "Lỗi! Không thể xóa Role mặc định";
            return RedirectToAction("Roles");
        }

        public IActionResult RoleActions(int id)
        {
            var viewModel = new List<RoleControllerActions>();
            var role = _roleServices.GetRolesByID(id);
            foreach (var action in _moduleActionServices.GetAllModuleActions())
            {
                ModuleControllers controllerData = new ModuleControllers();
                controllerData = _moduleControllerServices.GetModuleControllersByID(action.ControllerID);
                var data = new RoleControllerActions
                {
                    Controller_ID = controllerData.ControllerID,
                    ControllerName = controllerData.ControllerName,
                    ActionID = action.ActionID,
                    ActionName = action.ActionName,
                    Description = action.Description,
                };
                if (_roleServices.IsRoleInControllerAction(role.RoleID, controllerData.ControllerID, data.ActionID))
                {
                    data.Status = true;
                }
                else
                {
                    data.Status = false;
                }
                viewModel.Add(data);
            }

Views/Shared/NotFound.cshtml
@{
    ViewData["Title"] = ViewBag.ErrorMessage;
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    body {
        margin: 0;
        padding: 0;
    }

    p {
        margin: 0;
    }

    .layout-navbar-fixed .wrapper .content-wrapper {
        margin-top: 50px;
    }

    .error-page > .error-content {
        margin-left: 50px;
    }
</style>
<div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
        <div class="error-page">
            <br />
            <div class="col">
                <div class="error-content text-center" style="font-size:30px; font-weight:bold">
                    <h2><i class="fas fa-exclamation-triangle text-warning"></i> @ViewBag.ErrorMessage</h2>

                    <p>
                        @ViewBag.Msg
                        <br />
                        <a href="@Url.Action("Index","Home")">Bấm vào đây để trở về trang chủ</a>
                    </p>
                </div>
            </div>
            <div class="col">
                <img src="@ViewBag.ErrorImage" alt="error-@ViewBag.ErrorMessage" />
            </div>

            <!-- /.error-content -->
        </div>
        <!-- /.error-page -->
    </section>
    <!-- /.content -->
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebTool</title>
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/lib/fontawesome-free/css/all.min.css">
    <!-- iCheck for checkboxes and radio inputs -->
    <link rel="stylesheet" href="/lib/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="~/lib/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- Select2 -->
    <link rel="stylesheet" href="~/lib/select2/css/select2.min.css">
    <link rel="stylesheet" href="~/lib/select2-bootstrap4-theme/select2-bootstrap4.min.css">
    <!-- DataTables -->
    <link rel="stylesheet" href="~/lib/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/lib/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="~/lib/datatables-buttons/css/buttons.bootstrap4.min.css">
    <link rel="stylesheet" href="~/lib/datatables-fixedheader/css/fixedHeader.bootstrap4.min.css">
    <link rel="stylesheet" href="~/lib/datatables-select/css/select.bootstrap4.min.css">
    <link rel="stylesheet" href="~/lib/datatables-scroller/css/scroller.bootstrap4.min.css">
    <link rel="stylesheet" href="~/lib/datatables-checkboxes/css/dataTables.checkboxes.css">
    <!-- Toastr -->
    <link rel="stylesheet" href="~/lib/toastr/toastr.min.css">
    <!-- Bootstrap Toggle -->
    <link rel="stylesheet" href="~/lib/bootstrap-toggle/css/bootstrap-toggle.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/lib/admin-lte/css/adminlte.min.css">
    <link rel="stylesheet" href="~/css/site_default.css">
</head>
<body class="control-sidebar-slide-open layout-navbar-fixed sidebar-collapse">
    <div class="wrapper">
        @if (User.Identity.IsAuthenticated)
        {
            <header>
                <nav class="main-header navbar navbar-expand navbar-dark border-bottom-0">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="navbar-brand" role="button" asp-area="" asp-controller="Home" asp-action="Index">
                                <img src="/logo_compact_white_200x200.png" width="38" height="38" style="vertical-align: middle;" alt="">
                            </a>
                        </li>
                        <li class="nav-item d-none d-sm-inline-block">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Trang chủ</a>
                        </li>
                        <li class="nav-item d-none d-sm-inline-block">
                            <a class="nav-link" asp-area="" asp-controller="BaoHiemTuNguyen" asp-action="KhachHangThanhToanBHTN">Bảo hiểm tự nguyện</a>
                        </li>



                        @if (User.IsInRole("Admin"))
                        {
                            @*dropdown-hover*@
                            <li class="nav-item dropdown dropdown-hover">
                                <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link dropdown-toggle">Phân quyền</a>
                                <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow">
                                    <li><a asp-area="" asp-controller="Permission" asp-action="Users" class="dropdown-item">Tài khoản người dùng </a></li>
                                    <li><a asp-area="" asp-controller="Permission" asp-action="Roles" class="dropdown-item">Vai trò hệ thống</a></li>
                                    <li><a asp-area="" asp-controller="Permission" asp-action="ModuleController" class="dropdown-item">ModuleControllers</a></li>
                                    <li><a asp-area="" asp-controller="Permission" asp-action="ModuleAction" class="dropdown-item">ModuleActions</a></li>
                                </ul>
                            </li>
                        }

                    </ul>
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <partial name="_LoginStatusPartial" />
                        </li>
                    </ul>
                </nav>
            </header>
            <div class="content-wrapper">
                @RenderBody()
            </div>
        }

        <!-- jQuery -->
        <script src="~/lib/jquery/jquery.min.js"></script>
        <!-- Bootstrap 4 -->
        <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
        <!-- Select2 -->
        <script src="~/lib/select2/js/select2.full.min.js"></script>
        <!-- InputMask -->
        <script src="~/lib/moment/moment.min.js"></script>
        <script src="~/lib/moment/moment-with-locales.min.js"></script>
        <script src="~/lib/moment/locales.min.js"></script>
        <script src="~/lib/inputmask/jquery.inputmask.min.js"></script>
        <!-- Tempusdominus Bootstrap 4 -->
        <script src="~/lib/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
        <!-- bs-custom-file-input -->
        <script src="~/lib/bs-custom-file-input/bs-custom-file-input.min.js"></script>
        <!-- jquery-validation -->
        <script src="~/lib/jquery-validation/jquery.validate.min.js"></script>
        <script src="~/lib/jquery-validation/additional-methods.min.js"></script>
        <!-- DataTables  & Plugins -->
        <script src="~/lib/datatables/jquery.dataTables.min.js"></script>
        <script src="~/lib/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
        <script src="~/lib/datatables-responsive/js/dataTables.responsive.min.js"></script>
        <script src="~/lib/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
        <script src="~/lib/datatables-buttons/js/dataTables.buttons.min.js"></script>
        <script src="~/lib/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
        <script src="~/lib/jszip/jszip.min.js"></script>
        <script src="~/lib/pdfmake/pdfmake.min.js"></script>
        <script src="~/lib/pdfmake/vfs_fonts.js"></script>
        <script src="~/lib/datatables-buttons/js/buttons.html5.min.js"></script>
        <script src="~/lib/datatables-buttons/js/buttons.print.min.js"></script>
        <script src="~/lib/datatables-buttons/js/buttons.colVis.min.js"></script>
        <script src="~/lib/datatables-select/js/dataTables.select.min.js"></script>
        <script src="~/lib/datatables-select/js/select.bootstrap4.min.js"></script>
        <script src="~/lib/datatables-fixedheader/js/dataTables.fixedHeader.min.js"></script>
        <script src="~/lib/datatables-fixedheader/js/fixedHeader.bootstrap4.min.js"></script>
        <script src="~/lib/datatables-scroller/js/dataTables.scroller.min.js"></script>
        <script src="~/lib/datatables-scroller/js/scroller.bootstrap4.min.js"></script>
        <script src="~/lib/datatables-checkboxes/js/dataTables.checkboxes.min.js"></script>
        <!-- Toastr -->
        <script src="~/lib/toastr/toastr.min.js"></script>
        <!-- Bootstrap Toggle -->
        <script src="~/lib/bootstrap-toggle/js/bootstrap-toggle.min.js"></script>
        <!-- AdminLTE App -->
        <script src="~/lib/admin-lte/js/adminlte.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)
    </div>
</body>
</html>

Views/Shared/_LoginStatusPartial.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@


@if (User.Identity.IsAuthenticated)
{
    <a class="nav-link" href="/User/Logout">@User.Identity.Name (IP: @Context.Connection.RemoteIpAddress.MapToIPv4().ToString())</a>
}
else
{
    <a class="nav-link" href="/User/Login">Đăng nhập</a>
}